import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { prisma } from '@velora/db'
import type { CrashNarrativeContent, EqualizerBriefing, ComparableCohort, LiabilitySignal, SettlementContext, AttorneyMatch } from '@velora/shared'
import { SharePanel } from '@/components/crash/SharePanel'

interface ReportPageProps {
  params: Promise<{ crashId: string }>
}

export async function generateMetadata({ params }: ReportPageProps): Promise<Metadata> {
  const { crashId } = await params
  const crash = await prisma.crash.findUnique({
    where: { id: crashId },
    select: { crashDate: true, cityName: true, county: true, stateCode: true, crashSeverity: true },
  })

  if (!crash) return { title: 'Report Not Found' }

  const location = [crash.cityName, crash.county, crash.stateCode].filter(Boolean).join(', ')
  const date = crash.crashDate.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  return {
    title: `Crash Equalizer Report — ${location} | Velora`,
    description: `Crash Equalizer report for ${location} on ${date}. Comparable crashes, liability signals, and settlement estimates.`,
    openGraph: {
      title: `Crash Equalizer Report — ${location}`,
      description: `See comparable crashes, liability analysis, and settlement estimates for this crash in ${location}.`,
      type: 'article',
      images: [`/api/og/equalizer/${crashId}`],
    },
  }
}

export default async function ReportPage({ params }: ReportPageProps) {
  const { crashId } = await params
  const crash = await prisma.crash.findUnique({
    where: { id: crashId },
    include: {
      vehicles: true,
      persons: { select: { id: true, personType: true, injuryStatus: true } },
      narratives: { take: 1, orderBy: { generatedAt: 'desc' } },
      equalizer: true,
    },
  })

  if (!crash) notFound()

  const location = [crash.streetAddress, crash.cityName, crash.county].filter(Boolean).join(', ')
  const date = crash.crashDate.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const narrative = crash.narratives[0]
  const narrativeContent = narrative?.content as unknown as CrashNarrativeContent | undefined

  const equalizerData = crash.equalizer
  const briefing: EqualizerBriefing | null = equalizerData
    ? {
        comparable: equalizerData.comparableCohort as unknown as ComparableCohort,
        liability: equalizerData.liabilitySignals as unknown as LiabilitySignal[],
        settlement: equalizerData.settlementContext as unknown as SettlementContext,
        attorneyMatches: equalizerData.attorneyMatches as unknown as AttorneyMatch[],
        sections: equalizerData.briefingSections as unknown as EqualizerBriefing['sections'],
      }
    : null

  return (
    <main className="mx-auto max-w-3xl px-4 py-8 print:p-0">
      {/* Branding Header */}
      <div className="mb-8 border-b border-gray-200 pb-6 dark:border-gray-700">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
              Crash Equalizer Report
            </h1>
            <p className="mt-1 text-sm text-gray-500">
              Generated by Velora — {new Date().toLocaleDateString('en-US')}
            </p>
          </div>
          <div className="print:hidden">
            <SharePanel crashId={crash.id} location={location} />
          </div>
        </div>
      </div>

      {/* Crash Summary */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Crash Summary</h2>
        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <InfoCard label="Date" value={date} />
          <InfoCard label="Location" value={location} />
          <InfoCard label="Severity" value={(crash.crashSeverity ?? 'Unknown').replace(/_/g, ' ')} />
          <InfoCard label="Vehicles" value={String(crash.vehicles.length)} />
        </div>
        {narrativeContent?.summary && (
          <p className="mt-4 text-sm text-gray-600 dark:text-gray-400">
            {narrativeContent.summary}
          </p>
        )}
      </section>

      {/* Equalizer Results */}
      {briefing && (
        <>
          {/* Comparable Crashes */}
          <section className="mb-8">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
              Comparable Crashes
            </h2>
            <p className="mt-1 text-sm text-gray-500">
              {briefing.comparable.matchCount} similar crashes found
              {briefing.comparable.confidenceLevel ? ` (${briefing.comparable.confidenceLevel} confidence)` : ''}
            </p>
          </section>

          {/* Liability Signals */}
          {briefing.liability.length > 0 && (
            <section className="mb-8">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                Liability Signals
              </h2>
              <div className="mt-3 space-y-2">
                {briefing.liability.map((signal, i) => (
                  <div
                    key={i}
                    className="flex items-start gap-3 rounded-lg border border-gray-200 p-3 dark:border-gray-700"
                  >
                    <span
                      className={`mt-0.5 inline-block h-2 w-2 rounded-full ${
                        signal.indicator === 'STRONG_LIABILITY'
                          ? 'bg-green-500'
                          : signal.indicator === 'PARTIAL_LIABILITY'
                            ? 'bg-amber-500'
                            : 'bg-gray-400'
                      }`}
                    />
                    <div>
                      <div className="text-sm font-medium text-gray-900 dark:text-white">
                        {signal.rule.replace(/_/g, ' ')}
                      </div>
                      <div className="text-xs text-gray-500">{signal.explanation}</div>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Settlement Context */}
          {briefing.settlement && (
            <section className="mb-8">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                Settlement Context
              </h2>
              <div className="mt-3 rounded-lg bg-blue-50 p-4 dark:bg-blue-900/20">
                <div className="text-center">
                  <div className="text-sm text-gray-600 dark:text-gray-400">Estimated Range</div>
                  <div className="mt-1 text-2xl font-bold text-gray-900 dark:text-white">
                    ${briefing.settlement.adjustedRange.low.toLocaleString()} —{' '}
                    ${briefing.settlement.adjustedRange.high.toLocaleString()}
                  </div>
                </div>
              </div>
              <p className="mt-2 text-xs text-gray-500">
                Disclaimer: Settlement ranges are estimates based on comparable crashes and should not
                be considered legal advice.
              </p>
            </section>
          )}
        </>
      )}

      {/* Footer */}
      <footer className="mt-12 border-t border-gray-200 pt-4 text-center text-xs text-gray-400 dark:border-gray-700">
        <p>This report was generated by Velora, a crash intelligence platform.</p>
        <p className="mt-1">
          <a href="/" className="text-blue-600 hover:underline dark:text-blue-400">
            velora.com
          </a>
        </p>
      </footer>
    </main>
  )
}

function InfoCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-gray-200 px-4 py-3 dark:border-gray-700">
      <div className="text-xs font-medium uppercase text-gray-400">{label}</div>
      <div className="mt-1 text-sm font-semibold text-gray-900 dark:text-white">{value}</div>
    </div>
  )
}
