import TimelineWeb from '@/components/case/TimelineWeb'
import { displayName } from '@velora/shared'

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000'

async function fetchSharedCase(token: string) {
  try {
    const res = await fetch(`${API}/api/case/shared/${token}`, {
      next: { revalidate: 60 },
    })
    if (!res.ok) {
      if (res.status === 410) return { error: 'expired' as const }
      if (res.status === 403) return { error: 'invalid' as const }
      return { error: 'not_found' as const }
    }
    return { data: await res.json() }
  } catch {
    return { error: 'unavailable' as const }
  }
}

export default async function SharedCasePage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const result = await fetchSharedCase(token)

  if (result.error) {
    const messages: Record<string, { title: string; desc: string }> = {
      expired: { title: 'Link Expired', desc: 'This share link has expired. Ask the case owner to generate a new one.' },
      invalid: { title: 'Invalid Link', desc: 'This share link is not valid.' },
      not_found: { title: 'Case Not Found', desc: 'The case associated with this link could not be found.' },
      unavailable: { title: 'Service Unavailable', desc: 'Unable to load the case. Please try again later.' },
    }
    const msg = messages[result.error] || messages.unavailable!

    return (
      <div className="flex min-h-screen items-center justify-center bg-gray-50">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900">{msg.title}</h1>
          <p className="mt-2 text-gray-500">{msg.desc}</p>
          <a href="/" className="mt-4 inline-block text-blue-600 hover:underline">Go Home</a>
        </div>
      </div>
    )
  }

  const { matter, timeline, entities, facts } = result.data

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Shared banner */}
      <div className="border-b border-blue-200 bg-blue-50 px-6 py-3 text-center text-sm text-blue-700">
        Shared case view (read-only) — Generated by Velora
      </div>

      {/* Header */}
      <header className="border-b border-gray-200 bg-white px-6 py-4">
        <div className="mx-auto max-w-5xl">
          <h1 className="text-lg font-semibold text-gray-900">Case Overview</h1>
          <div className="mt-1 flex flex-wrap gap-4 text-sm text-gray-500">
            <span>Status: {displayName(matter.status)}</span>
            {matter.accidentDate && (
              <span>Accident: {new Date(matter.accidentDate).toLocaleDateString()}</span>
            )}
            {matter.stateCode && <span>State: {matter.stateCode}</span>}
          </div>
        </div>
      </header>

      <div className="mx-auto flex max-w-5xl flex-col gap-6 p-6 lg:flex-row">
        {/* Entities sidebar */}
        <aside className="w-full shrink-0 lg:w-56">
          <div className="rounded-xl border border-gray-200 bg-white p-4">
            <h2 className="mb-3 text-sm font-semibold text-gray-700">Key Entities</h2>
            {entities.length > 0 ? (
              <ul className="space-y-2">
                {entities.map((e: { type: string; name: string; confidence: number }, i: number) => (
                  <li key={i} className="text-sm">
                    <span className="text-gray-800">{e.name}</span>
                    <span className="ml-2 text-xs text-gray-400">{displayName(e.type)}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-xs text-gray-400">No entities yet.</p>
            )}
          </div>
        </aside>

        {/* Timeline */}
        <main className="min-w-0 flex-1">
          <div className="rounded-xl border border-gray-200 bg-white p-4">
            <h2 className="mb-3 text-sm font-semibold text-gray-700">Timeline</h2>
            <TimelineWeb events={timeline} matterId="shared" />
          </div>
        </main>

        {/* Facts */}
        <aside className="w-full shrink-0 lg:w-56">
          <div className="rounded-xl border border-gray-200 bg-white p-4">
            <h2 className="mb-3 text-sm font-semibold text-gray-700">Known Facts</h2>
            {facts.length > 0 ? (
              <ul className="space-y-2">
                {facts.map((f: { subject: string; predicate: string; object: string }, i: number) => (
                  <li key={i} className="text-sm text-gray-700">
                    <span className="font-medium">{f.subject}</span>{' '}
                    <span className="text-gray-400">{f.predicate.replace(/_/g, ' ')}</span>{' '}
                    <span className="font-medium">{f.object}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-xs text-gray-400">No facts yet.</p>
            )}
          </div>
        </aside>
      </div>
    </div>
  )
}
